### PR TITLE
fixed validation timeout query setting error

### PR DESCRIPTION
**Pull request by andrew-g-za**
Hi,
Could you please take a look at this fix and pull it in?

Thanks!

### CODE REVIEW

**Comment by mtakaki** [comment]
Good catch!!

**Comment by andrew-g-za** [comment]
👍  
will you be pushing a new build back to maven?

**Comment by mtakaki** [comment]
Yep! I just pushed it. The version is `1.0.3`.
Thanks again for spotting and fixing this!

**Comment by andrew-g-za** [comment]
awesome, thanks!
by the way, I think your testcases could be made much easier by testing the _config_ that is created by the DataSourceFactory, rather than spinning up a database connection itself - after all we dont really need to test Hikari's datasource, only that we create the right HikariConfig from the DataSourceFactory configuration.

What do you think?

**Comment by mtakaki** [comment]
I agree, actually. My intention was to have it as an integration test, so I wanted to ensure it's usable.
As we could have an unit test that ensures the configuration is created, but not necessarily works.
But you're right, I missed this bug here. I'll create an additional unit test as you suggested.

**Pull request merged**
